version: '3.8'

services:
  mas-payments:
    build: .
    ports:
      - "5002:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Pooling=true; Database=prt; Username=devw; Password=123; Timeout=5;

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: prt
      POSTGRES_USER: devw
      POSTGRES_PASSWORD: 123
    ports:
      - "5401:5432"
    volumes:
      - p_payments:/var/lib/postgresql/data

volumes:
  p_payments:
